changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: Breaking changes
      labels:
        - breaking change
    - title: Security
      labels:
        - security
    - title: Features
      labels:
        - enhancement
        - protocol
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
